[versions]

kotlin = "1.9.10"
ksp = "1.0.13"
kspPlugin = "1.9.10-1.0.13"  # Must be "$kotlin-$ksp"
composeCompiler = "1.5.3"
hilt = "2.48.1"
lifecycle = "2.6.2"
room = "2.5.2"


[libraries]

androidx-lifecycle-runtimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

google-dagger-hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
google-dagger-hiltCompiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

androidx-compose-bom = "androidx.compose:compose-bom:2023.10.00"

androidx-core-ktx = "androidx.core:core-ktx:1.12.0"
androidx-activity-compose = "androidx.activity:activity-compose:1.8.0"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.7.4"
androidx-hilt-navigationCompose = "androidx.hilt:hilt-navigation-compose:1.0.0"
plrapps-mapcompose = "ovh.plrapps:mapcompose:2.9.4"

junit = "junit:junit:4.13.2"
androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-rules = "androidx.test:rules:1.5.0"
androidx-test-extJunit = "androidx.test.ext:junit:1.1.5"


[plugins]

android-application = "com.android.application:8.1.2"
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
