name: Test

on: [ push, workflow_dispatch ]

env:
  API_LEVEL: 31
  ARCH: x86_64

jobs:
  run-tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Cache AVD
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-v4

      - name: Create AVD and generate a snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{env.API_LEVEL}}
          arch: ${{env.ARCH}}
          force-avd-creation: false
          # https://developer.android.com/studio/run/emulator-commandline
          emulator-options: -no-audio -no-window -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          script: echo "Generated AVD snapshot for caching"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run instrumented tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{env.API_LEVEL}}
          arch: ${{env.ARCH}}
          force-avd-creation: false
          emulator-options: -no-audio -no-window -no-snapshot-save -no-boot-anim -camera-back none -camera-front none -gpu swiftshader_indirect
          script: ./gradlew connectedDebugAndroidTest
